export const GET_ALL_PRODUCTS = "GET_ALL_PRODUCTS";
export const DELETE_PRODUCT = "DELETE_PRODUCT";
export const PRODUCT_LOADING = "PRODUCT_LOADING";
export const PRODUCT_LOADING_FAILED = "PRODUCT_LOADING_FAILED";
